export const books = [
    {
      id: '1',
      title: 'React Basics',
      author: 'Jewel',
      category: 'Tech',
      price: 30,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '2',
      title: 'Advanced React',
      author: 'Jewel',
      category: 'Science',
      price: 40,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '3',
      title: 'JavaScript Essentials',
      author: 'Jewel',
      category: 'Tech',
      price: 25,
      available: false,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '4',
      title: 'Node.js in Depth',
      author: 'Jewel',
      category: 'Tech',
      price: 35,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '5',
      title: 'MongoDB Guide',
      author: 'Jewel',
      category: 'Tech',
      price: 28,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '6',
      title: 'Express Quickstart',
      author: 'Jewel',
      category: 'Tech',
      price: 20,
      available: false,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '7',
      title: 'TypeScript Handbook',
      author: 'Jewel',
      category: 'Tech',
      price: 33,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '8',
      title: 'Frontend Masters',
      author: 'Jewel',
      category: 'Tech',
      price: 45,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '9',
      title: 'CSS for Pros',
      author: 'Jewel',
      category: 'Tech',
      price: 18,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '10',
      title: 'HTML Deep Dive',
      author: 'Jewel',
      category: 'Tech',
      price: 22,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '11',
      title: 'React Native Intro',
      author: 'Jewel',
      category: 'Tech',
      price: 38,
      available: false,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '12',
      title: 'Vue.js in Action',
      author: 'Jewel',
      category: 'Tech',
      price: 29,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '13',
      title: 'Angular Starter',
      author: 'Jewel',
      category: 'Tech',
      price: 31,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '14',
      title: 'Next.js Complete',
      author: 'Jewel',
      category: 'Tech',
      price: 42,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '15',
      title: 'Redux Toolkit 101',
      author: 'Jewel',
      category: 'Tech',
      price: 36,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '16',
      title: 'APIs with REST',
      author: 'Jewel',
      category: 'Tech',
      price: 27,
      available: false,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '17',
      title: 'GraphQL Mastery',
      author: 'Jewel',
      category: 'Tech',
      price: 39,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '18',
      title: 'Docker for Devs',
      author: 'Jewel',
      category: 'Tech',
      price: 34,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '19',
      title: 'DevOps Handbook',
      author: 'Jewel',
      category: 'Tech',
      price: 41,
      available: false,
      image: 'https://via.placeholder.com/150',
    },
    {
      id: '20',
      title: 'Testing with Jest',
      author: 'Jewel',
      category: 'Tech',
      price: 26,
      available: true,
      image: 'https://via.placeholder.com/150',
    },
  ];